### ISSUE TITLE
Unable to locate message source for category 'kvenum'

### ISSUE THREAD

**Issue by devleaks** [kartik-v/yii2-helpers#13]
I'm using a simple call to Enum::getBrowser() and now get this error since I updated to yesterday's update.

Enum.php, line 838: "opera" => Yii::t("kvenum", "Opera").

Many thanks.
Pierre

**Comment by kartik-v** [comment]
The latest release has Yii translations enabled instead of hardcoded english messages.

You probably have a app language other than what is available in the messages folder of the extension. Submit a PR for your language message file (check the `messages` folder and add a folder and the message file `kvenum.php` for your language).

**Comment by devleaks** [comment]
Ok thanks. I'll do it asap.
